namespace IDEK.Tools.ConsoleCommander;

/// <summary>
/// Attribute to mark a method as a <see cref="System.CommandLine"/> command.
/// </summary>
[AttributeUsage(AttributeTargets.Method, Inherited = false, AllowMultiple = true)]
public sealed class CommandAttribute : Attribute
{
    /// <summary>
    /// Array of each segment of the command tree path needed to invoke the command.
    /// </summary>
    public string[] Path { get; }
    
    /// <summary>
    /// Description of the command. Will show up in help text.
    /// </summary>
    public string Description { get; init; }
    
    //TODO: these are for later - it just autogenerated them pretty nicely
    // public string? HelpText { get; }
    // public string? Example { get; }
    // public string? ExampleDescription { get; }
    // public bool IsHidden { get; }
    // public bool IsDeprecated { get; }
    // public bool IsExperimental { get; }
    // public bool IsHiddenFromHelp { get; }
    // public bool IsHiddenFromCompletion { get; }
    
    /// <summary>
    /// Sets up a command line command with the given path
    /// </summary>
    /// <param name="path">array of each segment of the command tree path needed to invoke the command.</param>
    /// <exception cref="ArgumentNullException">If the path is null.</exception>
    /// <exception cref="ArgumentException">If the path is empty.</exception>
    /// <exception cref="ArgumentException">If one of the path segments contains a space or invalid character.</exception>
    public CommandAttribute(params string[] path)
    {
        if (path == null) throw new ArgumentNullException(nameof(path));
        if (path.Length == 0) throw new ArgumentException("Path cannot be empty", nameof(path));
        foreach (var segment in path)
        {
            if (segment.Contains(' ') || segment.Any(char.IsControl)) 
                throw new ArgumentException("Path segments cannot contain spaces or control characters", nameof(path));
        }
        
        Path = path;
    }

    ///<inheritdoc cref="CommandAttribute(string[])"/>
    /// <param name="path">A single string (space delimited) of the command tree path needed to invoke the command.</param>
    /// <remarks>This is a convenience constructor for when
    /// you have a relatively simple path and/or want to use
    /// string interpolation. Plays nicely with the other overload
    /// because everything needs to be space delimited in either case.
    /// </remarks>
    /// <exception cref="ArgumentNullException">If the path is null.</exception>
    /// <exception cref="ArgumentException">If the path is empty.</exception>
    /// <exception cref="ArgumentException">If one of the path segments contains an invalid character.</exception>
    public CommandAttribute(string path)
    {
        if (path == null) throw new ArgumentNullException(nameof(path));
        if (path.Length == 0) throw new ArgumentException("Path cannot be empty", nameof(path));
        if (path.Any(char.IsControl)) throw new ArgumentException("Path segments cannot contain control characters", nameof(path));
        Path = path.Split(' ', StringSplitOptions.RemoveEmptyEntries);
    }
}