name: .NET Core Unit Tests

on:
  push:
    branches: [ "main", "master", "beta" ]
  pull_request:
    branches: [ "main", "master", "beta" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build PlumbobModManager.Tests/PlumbobModManager.Tests.csproj --no-restore
    - name: Test
      run: dotnet test PlumbobModManager.Tests/PlumbobModManager.Tests.csproj --no-build --verbosity normal
